export const ENGLISH_WORDS_LIST: string[] = [
  // Pronouns & Articles
  "the", "a", "an", "i", "you", "he", "she", "it", "we", "they", "me", "him", "her", "us", "them",
  "my", "your", "his", "its", "our", "their", "mine", "yours", "hers", "ours", "theirs",
  "myself", "yourself", "himself", "herself", "itself", "ourselves", "themselves",
  "this", "that", "these", "those", "who", "whom", "whose", "which", "what", "whatever",

  // Conjunctions & Prepositions
  "and", "but", "or", "so", "because", "although", "though", "while", "whereas", "since",
  "until", "unless", "if", "whether", "as", "than", "then", "now", "here", "there",
  "about", "above", "across", "after", "against", "along", "among", "around", "at", "before",
  "behind", "below", "beneath", "beside", "between", "beyond", "by", "down", "during", "except",
  "for", "from", "in", "inside", "into", "near", "of", "off", "on", "onto", "out", "outside",
  "over", "past", "through", "throughout", "to", "toward", "under", "underneath", "until", "up",
  "upon", "with", "within", "without",

  // Verbs & Auxiliaries
  "am", "is", "are", "was", "were", "be", "been", "being", "have", "has", "had", "having",
  "do", "does", "did", "doing", "can", "could", "will", "would", "shall", "should", "may", "might", "must",
  "go", "went", "gone", "going", "goes", "come", "came", "coming", "comes",
  "make", "made", "making", "makes", "take", "took", "taken", "taking", "takes",
  "get", "got", "gotten", "getting", "gets", "say", "said", "saying", "says",
  "think", "thought", "thinking", "thinks", "know", "knew", "known", "knowing", "knows",
  "see", "saw", "seen", "seeing", "sees", "want", "wanted", "wanting", "wants",
  "look", "looked", "looking", "looks", "use", "used", "using", "uses",
  "find", "found", "finding", "finds", "give", "gave", "given", "giving", "gives",
  "tell", "told", "telling", "tells", "work", "worked", "working", "works",
  "call", "called", "calling", "calls", "try", "tried", "trying", "tries",
  "ask", "asked", "asking", "asks", "feel", "felt", "feeling", "feels",
  "become", "became", "becoming", "becomes", "leave", "left", "leaving", "leaves",
  "keep", "kept", "keeping", "keeps", "start", "started", "starting", "starts",
  "begin", "began", "begun", "beginning", "begins", "help", "helped", "helping", "helps",
  "talk", "talked", "talking", "talks", "write", "wrote", "written", "writing", "writes",
  "read", "reading", "reads", "run", "ran", "running", "runs",
  "play", "played", "playing", "plays", "move", "moved", "moving", "moves",
  "live", "lived", "living", "lives", "believe", "believed", "believing", "believes",
  "bring", "brought", "bringing", "brings", "happen", "happened", "happening", "happens",
  "hear", "heard", "hearing", "hears", "meet", "met", "meeting", "meets",
  "sit", "sat", "sitting", "sits", "stand", "stood", "standing", "stands",
  "pay", "paid", "paying", "pays", "lose", "lost", "losing", "loses",
  "win", "won", "winning", "wins", "understand", "understood", "understanding", "understands",
  "speak", "spoke", "spoken", "speaking", "speaks", "spend", "spent", "spending", "spends",
  "grow", "grew", "grown", "growing", "grows", "allow", "allowed", "allowing", "allows",
  "add", "added", "adding", "adds", "buy", "bought", "buying", "buys",
  "sell", "sold", "selling", "sells", "send", "sent", "sending", "sends",
  "build", "built", "building", "builds", "fall", "fell", "fallen", "falling", "falls",
  "cut", "cutting", "cuts", "learn", "learned", "learning", "learns",
  "eat", "ate", "eaten", "eating", "eats", "drink", "drank", "drunk", "drinking", "drinks",
  "sleep", "slept", "sleeping", "sleeps", "love", "loved", "loving", "loves",
  "hate", "hated", "hating", "hates", "like", "liked", "liking", "likes",

  // Nouns
  "computer", "beautiful", "tomorrow", "today", "yesterday", "tonight",
  "morning", "afternoon", "evening", "night", "day", "week", "month", "year", "decade", "century",
  "time", "person", "people", "man", "woman", "child", "children", "family", "friend", "friends",
  "life", "world", "school", "student", "teacher", "class", "study", "work", "job", "office",
  "company", "business", "system", "program", "software", "data", "information", "file", "folder",
  "report", "budget", "meeting", "project", "manager", "director", "president", "executive",
  "employee", "employer", "staff", "team", "group", "member", "customer", "client", "user",
  "service", "product", "market", "sales", "price", "cost", "money", "cash", "bank", "card",
  "account", "payment", "order", "delivery", "shipping", "address", "phone", "email", "message",
  "chat", "social", "media", "network", "internet", "website", "page", "site", "link", "code",
  "developer", "designer", "engineer", "doctor", "nurse", "patient", "hospital", "clinic",
  "medicine", "health", "illness", "disease", "pain", "headache", "fever", "treatment", "care",
  "body", "mind", "soul", "heart", "brain", "eye", "ear", "nose", "mouth", "hand", "foot", "face",
  "head", "hair", "skin", "blood", "bone", "water", "food", "drink", "milk", "tea", "coffee",
  "sugar", "salt", "pepper", "fruit", "apple", "banana", "orange", "vegetable", "bread", "butter",
  "cheese", "meat", "chicken", "fish", "rice", "soup", "salad", "cake", "cookie", "chocolate",
  "sweet", "sour", "bitter", "spicy", "hot", "cold", "warm", "cool", "ice", "fire", "wind", "rain",
  "snow", "sun", "moon", "star", "sky", "cloud", "earth", "land", "sea", "ocean", "river", "lake",
  "mountain", "hill", "forest", "tree", "flower", "grass", "plant", "animal", "dog", "cat", "bird",
  "fish", "horse", "cow", "pig", "sheep", "monkey", "lion", "tiger", "bear", "elephant",
  "city", "town", "village", "country", "state", "nation", "universe", "space", "planet",
  "street", "road", "path", "bridge", "house", "home", "apartment", "room", "bedroom", "bathroom",
  "kitchen", "living", "door", "window", "wall", "floor", "roof", "garden", "yard", "park",
  "store", "shop", "mall", "market", "supermarket", "restaurant", "hotel", "library", "museum",
  "theater", "cinema", "church", "temple", "mosque", "station", "airport", "train", "bus",
  "car", "truck", "bicycle", "motorcycle", "plane", "boat", "ship", "travel", "trip", "journey",
  "flight", "ticket", "passport", "bag", "suitcase", "camera", "map", "guide", "bed", "pillow",
  "blanket", "sheet", "towel", "soap", "shampoo", "brush", "toothpaste", "comb", "mirror",
  "paper", "pen", "pencil", "notebook", "book", "magazine", "newspaper", "letter", "envelope",
  "stamp", "box", "package", "gift", "present", "toy", "game", "sport", "ball", "player",
  "coach", "score", "match", "chess", "cards", "music", "song", "singer", "band", "concert",
  "album", "instrument", "guitar", "piano", "drums", "violin", "art", "artist", "painting",
  "drawing", "sculpture", "photo", "photographer", "picture", "image", "video", "movie", "film",
  "actor", "actress", "producer", "writer", "author", "poet", "poem", "story", "novel", "history",
  "science", "math", "physics", "chemistry", "biology", "nature", "environment", "energy",
  "power", "light", "dark", "sound", "noise", "silence", "voice", "word", "sentence", "phrase",
  "language", "english", "spanish", "french", "german", "italian", "chinese", "japanese",
  "korean", "arabic", "hindi", "sanskrit", "latin", "greek", "geography", "culture", "society",
  "government", "politics", "law", "rule", "policy", "right", "duty", "freedom", "peace", "war",
  "army", "soldier", "weapon", "gun", "knife", "bomb", "attack", "defense", "victory", "defeat",
  "treaty", "alliance", "union", "organization", "association", "club", "crowd", "public",
  "private", "secret", "mystery", "truth", "lie", "opinion", "fact", "evidence", "proof",
  "argument", "reason", "logic", "idea", "concept", "theory", "hypothesis", "experiment",
  "result", "conclusion", "analysis", "research", "wisdom", "intelligence",

  // Adjectives & Adverbs
  "great", "huge", "large", "big", "small", "little", "tiny", "tall", "short", "long", "wide",
  "narrow", "deep", "shallow", "high", "low", "top", "bottom", "middle", "side", "front", "back",
  "left", "right", "center", "corner", "edge", "border", "limit", "range", "space", "time",
  "hot", "cold", "warm", "cool", "mild", "dry", "wet", "humid", "rainy", "sunny", "cloudy",
  "windy", "stormy", "snowy", "foggy", "misty", "clear", "nice", "fine", "lovely", "perfect",
  "okay", "ok", "yes", "no", "maybe", "perhaps", "possibly", "probably", "definitely", "sure",
  "certainly", "absolutely", "indeed", "really", "truly", "actually", "basically", "exactly",
  "precisely", "nearly", "almost", "around", "approximately", "always", "never", "sometimes",
  "often", "usually", "frequently", "seldom", "rarely", "hardly", "scarcely", "ever", "once",
  "twice", "again", "still", "yet", "already", "just", "only", "even", "also", "too", "either",
  "neither", "nor", "good", "bad", "terrible", "horrible", "awful", "wonderful", "amazing",
  "awesome", "fantastic", "excellent", "beautiful", "ugly", "pretty", "handsome", "cute",
  "happy", "sad", "angry", "excited", "bored", "tired", "exhausted", "sleepy", "hungry",
  "thirsty", "full", "empty", "heavy", "light", "strong", "weak", "fast", "slow", "quick",
  "rapid", "sudden", "gradual", "easy", "difficult", "hard", "soft", "smooth", "rough",
  "sharp", "dull", "clean", "dirty", "neat", "messy", "smart", "clever", "wise", "foolish",
  "stupid", "crazy", "mad", "silly", "funny", "serious", "please", "thanks", "welcome",
  "hello", "hi", "hey", "bye", "goodbye", "brother", "sister", "mother", "father", "friend",
  // Crucial words missing
  "how", "why", "where", "when", "who", "whom", "whose", "which", "what", "very", "normal", "keyboard",
  "containing", "contain", "contains", "contained", "computer", "mouse", "monitor", "window", "door",
  "house", "street", "city", "country", "world", "words", "word", "is", "this", "like", "apple", "banana",
  "carrot", "orange", "elephant"
];

export const ENGLISH_WORDS_SET = new Set(ENGLISH_WORDS_LIST);
